name: Android Release CI

on:
  push:
    branches:
      - 'release*'

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: setup Java JDK
        uses: actions/setup-java@v4.3.0
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Grant Permissions For gradlew
        run: chmod +x gradlew
      - name: Run Unit Test
        run: ./gradlew test

  signing_apk:
    runs-on: [ubuntu-latest]
    needs: [unit_tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: setup Java JDK
        uses: actions/setup-java@v4.3.0
        with:
         java-version: 17
         distribution: 'zulu'
         cache: gradle
      - name: Grant Permissions For gradlew
        run: chmod +x gradlew
#      - name: Version Bump
#        uses: chkfung/android-version-actions@v1.2.3
#        with:
#         gradlePath: app/build.gradle.kts
#         versionCode: ${{ github.run_number }}
      - name: Generate Release Bundle
        run: ./gradlew bundleRelease
      - name: sign Release
        uses: r0adkll/sign-android-release@v1
          # ID used to access action output, use later
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ALIAS_KEY }}
          keyPassword: ${{ secrets.ALIAS_KEY_PASSWORD }}
      - name: Upload Release Build
        uses: actions/upload-artifact@v4
        with:
          name: release.aab
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: Download Release Build
        uses: actions/download-artifact@v4
        with:
         name: release.apk


#  qa_build:
#    runs-on: [ubuntu-latest]
#    needs: [signing_apk]
#    steps:
#      - name: upload artifact to Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{secrets.FIREBASE_PROJECT_ID}}
#          token: ${{secrets.FIREBASE_TOKEN}}
#          groups: QA
#          file: release.aab
